const mongoose=require('mongoose')

const settingSchema=mongoose.Schema({
    coinValue:{
        type:Number,
        default:0
    },
    regCoin:{
        type:Number,
        default:0
    },
    bkash:{
        type:Number,
        default:0
    },
    paytm:{
        type:Number,
        default:0
    },
    refer:{
        type:Number,
        default:0
    },
    cap1:{
        type:Number,
        default:0
    },
    minW:{
        type:Number,
        default:0
    },
    cap2:{
        type:Number,
        default:0
    },
    cap3:{
        type:Number,
        default:0
    },
    cap4:{
        type:Number,
        default:0
    },
    offer:{
        type:Number,
        default:0
    },
    firstCaptchaDelayTime:{
        type:Number,
        default:0
    },
    secondCaptchaDelayTime:{
        type:Number,
        default:0
    },
    thirdCaptchaDelayTime:{
        type:Number,
        default:0
    },
    watchDelayTime:{
        type:Number,
        default:0
    },fourthCaptchaDelayTime:{
        type:Number,
        default:0
    }
});
const Settings=mongoose.model('Settings',settingSchema)
module.exports=Settings

