const mongoose=require('mongoose')

const userSchema=mongoose.Schema({
    name:{
        type:String,
        require:true
    },
    phone:{
        type:String,
        require:true,
        unique:true
    },
    email:{
        type:String,
        require:true,
        unique:true
    },
    deviceId:{
        type:String,
        require:true,
        unique:true
    },
    password:{
        type:String,
        require:true
    },
    refer:{
        require:true,
        type:String
    },
    videoState:{
        type:Number,
        default:1,
    },
    myRefer:{
        require:true,
        type:String
    },
    coins:{
        type:Number
    },
    profileImage:{
        type:String
    },
    cap1LastPlay:{
        type:Number,
        default:0
    },
    cap2LastPlay:{
        type:Number,
        default:0
    },
    cap3LastPlay:{
        type:Number,
        default:0
    },
    cap4LastPlay:{
        type:Number,
        default:0
    },
    watchLastPlay:{
        type:Number,
        default:0
    }
});
const User=mongoose.model('Users',userSchema)
module.exports=User

